USE [master];
GO

CREATE DATABASE [DBI202_Group2_FlightMgmt];
GO

USE [DBI202_Group2_FlightMgmt];
GO

CREATE TABLE [Airports] (
	[ApID] VARCHAR(4) PRIMARY KEY,
	[ApName] NVARCHAR(MAX) NOT NULL,
	[Address] NVARCHAR(MAX) NOT NULL,
	[TimeOffset] INT NOT NULL,
	MaxWTCategory VARCHAR(1) NOT NULL
);

CREATE TABLE [Routes] (
	[RouteID] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
	[ArrICAO] VARCHAR(4) NOT NULL,
	[DepartICAO] VARCHAR(4) NOT NULL,
	[Distance] FLOAT NOT NULL
	CONSTRAINT fk_routes_airports_arr FOREIGN KEY (ArrICAO) REFERENCES Airports(ApID),
	CONSTRAINT fk_routes_airports_depart FOREIGN KEY (DepartICAO) REFERENCES Airports(ApID)
);

CREATE TABLE [Airlines] (
	[AirlineID] VARCHAR(3) PRIMARY KEY,
	[AirlineName] NVARCHAR(MAX) NOT NULL,
	[OperatingCountry] VARCHAR(2) NOT NULL,
	[Address] NVARCHAR(MAX) NOT NULL,
	[Email] NVARCHAR(255),
	[PhoneNum] NVARCHAR(20)
);

CREATE TABLE [FlightNums] (
	[FlightNum] VARCHAR(7) PRIMARY KEY,
	[RouteID] UNIQUEIDENTIFIER NOT NULL,
	[AirlineID] VARCHAR(3) NOT NULL,
	CONSTRAINT fk_flightnums_routes FOREIGN KEY (RouteID) REFERENCES Routes(RouteID),
	CONSTRAINT fk_flightnums_airlines FOREIGN KEY (AirlineID) REFERENCES Airlines(AirlineID)
);

CREATE TABLE [AircraftTypes] (
	[AcID] VARCHAR(4) PRIMARY KEY,
	[AcName] NVARCHAR(MAX) NOT NULL,
	[SeatCapacity] INT NOT NULL,
	[MaxDistance] FLOAT NOT NULL,
	[WTCategory] VARCHAR(1) NOT NULL
);

CREATE TABLE [FlightInstances] (
	[FlightID] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
	[Status] NVARCHAR(MAX),
	[ArrTime] DATETIME NOT NULL,
	[DepartTime] DATETIME NOT NULL,
	[AcID] VARCHAR(4) NOT NULL,
	[FlightNum] VARCHAR(7) NOT NULL,
	CONSTRAINT fk_flightinstances_flightnums FOREIGN KEY (FlightNum) REFERENCES FlightNums(FlightNum),
	CONSTRAINT fk_flightinstances_aircrafttypes FOREIGN KEY (AcID) REFERENCES AircraftTypes(AcID)
);

CREATE TABLE [Seats] (
	[SeatID] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
	[FlightID] UNIQUEIDENTIFIER NOT NULL,
	[Description] NVARCHAR(MAX),
	[Price] MONEY NOT NULL,
	[Seat] VARCHAR(5) NOT NULL,
	[isOccupied] BIT NOT NULL
	CONSTRAINT fk_seats_flightinstances FOREIGN KEY (FlightID) REFERENCES FlightInstances(FlightID)
);

CREATE TABLE [Transactions] (
	[TransactionID] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
	[Amount] MONEY NOT NULL,
	[PaymentMethod] NVARCHAR(MAX) NOT NULL,
	[PaymentTime] DATETIME NOT NULL,
	[isSuccess] BIT NOT NULL
);

CREATE TABLE [Passengers] (
	[PassengerID] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
	[FirstName] NVARCHAR(MAX) NOT NULL,
	[LastName] NVARCHAR(MAX) NOT NULL,
	[Email] NVARCHAR(255),
	[PassportNum] NVARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE [Booking] (
	[BookingID] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
	[SeatID] UNIQUEIDENTIFIER NOT NULL,
	[TransactionID] UNIQUEIDENTIFIER NOT NULL,
	[PassengerID] UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT fk_booking_seat FOREIGN KEY (SeatID) REFERENCES Seats(SeatID),
	CONSTRAINT fk_booking_passenger FOREIGN KEY (PassengerID) REFERENCES Passengers(PassengerID),
	CONSTRAINT fk_booking_transactions FOREIGN KEY (TransactionID) REFERENCES Transactions(TransactionID)
);
